## 다시 분석

### 모듈부터 없음
- 판다스 부터

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.23.2 (from pandas)
  Downloading numpy-2.1.2-cp311-cp311-win_amd64.whl.metadata (59 kB)
     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ---------------------------------------- 59.7/59.7 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in d:\01_programming\100_hugobank\mine\works-need-it-data-analysis\analenv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\01_programming\100_hugobank\mine\works-need-it-data-analysis\analenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   -- ------------------------------------- 0.6/11.6 MB 20.5 MB/s eta 0:00:01
   ----------- ---------------------------- 3.3/11.6 MB 42.0 MB/s eta 0:00:01
   --------------------- ------------------ 6.1/11.6 MB 48.7 MB/s eta 0:00:01
   ------------------------------- -------- 9.0/11.6 MB 52.3 MB/s eta 0:00:01
   ---------------------------------------  11.6/11.6 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 50.4 MB/s eta 0:00:00
Downloading numpy-2.1.2-cp311-cp311-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------ --------------------------------- 2.2/12.9 MB 46.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.8/12.9 MB 51.4 MB/s eta 0:00:01
   ---------------------- ----------------- 7.2/12.9 MB 51.1 MB/s eta 0:00:01
   ------------------------------ --------- 9.9/12.9 MB 52.7 MB/s eta 0:00:01
   -------------------------------------- - 12.5/12.9 MB 54.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 46.7 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
   ---------------------------------------- 0.0/508.0 kB ? eta -:--:--
   --------------------------------------- 508.0/508.0 kB 33.2 MB/s eta 0:00:00
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
   ---------------------------------------- 0.0/346.6 kB ? eta -:--:--
   --------------------------------------- 346.6/346.6 kB 10.8 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.1.2 pandas-2.2.3 pytz-2024.2 tzdata-2024.2

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install folium

Collecting folium
  Downloading folium-0.17.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.0-py3-none-any.whl.metadata (1.5 kB)
Collecting jinja2>=2.9 (from folium)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy in d:\01_programming\100_hugobank\mine\works-need-it-data-analysis\analenv\lib\site-packages (from folium) (2.1.2)
Collecting requests (from folium)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting xyzservices (from folium)
  Downloading xyzservices-2024.9.0-py3-none-any.whl.metadata (4.1 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=2.9->folium)
  Downloading MarkupSafe-3.0.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting charset-normalizer<4,>=2 (from requests->folium)
  Downloading charset_normalizer-3.4.0-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->folium)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->folium)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->folium)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading folium-0.17.0-py2.py3-none-any.whl (108 kB)
   ---------------------------------------- 0.0/108.4 kB ? eta -:--:--
   ---------------------------------------- 108.4/108.4 kB 2.1 MB/s eta 0:00:00
Downloading branca-0.8.0-py3-none-any.whl (25 kB)
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
   ---------------------------------------- 0.0/133.3 kB ? eta -:--:--
   ---------------------------------------- 133.3/133.3 kB 8.2 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
   ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
   ---------------------------------------- 64.9/64.9 kB 3.4 MB/s eta 0:00:00
Downloading xyzservices-2024.9.0-py3-none-any.whl (85 kB)
   ---------------------------------------- 0.0/85.1 kB ? eta -:--:--
   ---------------------------------------- 85.1/85.1 kB 4.7 MB/s eta 0:00:00
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
   ---------------------------------------- 0.0/167.3 kB ? eta -:--:--
   ---------------------------------------- 167.3/167.3 kB 5.1 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.0-cp311-cp311-win_amd64.whl (101 kB)
   ---------------------------------------- 0.0/101.8 kB ? eta -:--:--
   ---------------------------------------- 101.8/101.8 kB ? eta 0:00:00
Downloading idna-3.10-py3-none-any.whl (70 kB)
   ---------------------------------------- 0.0/70.4 kB ? eta -:--:--
   ---------------------------------------- 70.4/70.4 kB ? eta 0:00:00
Downloading MarkupSafe-3.0.1-cp311-cp311-win_amd64.whl (15 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
   ---------------------------------------- 0.0/126.3 kB ? eta -:--:--
   ---------------------------------------- 126.3/126.3 kB ? eta 0:00:00
Installing collected packages: xyzservices, urllib3, MarkupSafe, idna, charset-normalizer, certifi, requests, jinja2, branca, folium
Successfully installed MarkupSafe-3.0.1 branca-0.8.0 certifi-2024.8.30 charset-normalizer-3.4.0 folium-0.17.0 idna-3.10 jinja2-3.1.4 requests-2.32.3 urllib3-2.2.3 xyzservices-2024.9.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in d:\01_programming\100_hugobank\mine\works-need-it-data-analysis\analenv\lib\site-packages (24.0)
Collecting pip
  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.2-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   --- ------------------------------------ 0.2/1.8 MB 2.5 MB/s eta 0:00:01
   ------------------------------ --------- 1.4/1.8 MB 12.5 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 12.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-24.2

In [6]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5

### 부산 초등학교 정보 로드

In [1]:
import pandas as pd
import numpy as np

import folium
import json

from folium import Marker
from folium.plugins import MarkerCluster

In [2]:
df_busan_elementry = pd.read_excel('./2024년_부산_초등학교_학생수_최종정리.xlsx')

In [3]:
df_busan_elementry.head()

,지역,정보공시 학교코드,학교명,설립구분,제외여부,1학년 학생수,2학년 학생수,3학년 학생수,4학년 학생수,5학년 학생수,6학년 학생수,총학생수,교사수
0,연제구,S000003559,부산교육대학교부설초등학교,국립,N,79,95,95,95,95,95,560,29
1,중구,S020000625,광일초등학교,공립,N,32,43,36,36,49,62,262,17
2,중구,S020000626,남성초등학교,사립,N,90,89,83,69,44,63,438,23
3,남구,S020000628,대남초등학교,공립,N,64,40,67,44,38,56,314,19
4,남구,S020000629,대연초등학교,공립,N,112,130,130,151,152,187,871,48

### 각 학교별로 위치값 찾아서 매핑하기
- 아래 URL에 존재
    - https://www.data.go.kr/data/15021148/standard.do

In [4]:
# CSV파일 로드 하기
df_school_info = pd.read_csv('./전국초중등학교위치표준데이터.csv', encoding='EUC-KR')

In [5]:
df_school_info.tail(2)

,학교ID,학교명,학교급구분,설립일자,설립형태,본교분교구분,운영상태,소재지지번주소,소재지도로명주소,시도교육청코드,시도교육청명,교육지원청코드,교육지원청명,생성일자,변경일자,위도,경도,데이터기준일자,제공기관코드,제공기관명
11987,B000030436,새봄초등학교,초등학교,2021-03-01,공립,본교,운영,경기도 화성시 병점동 756-298,경기도 화성시 병점노을로 19,7530000,경기도교육청,7679000,경기도화성오산교육지원청,2013-11-29,2024-07-09,37.201463,127.029773,2024-09-20,B555223,재단법인한국지방교육행정연구재단
11988,B000007266,대구의흥초등학교,초등학교,1911-01-07,공립,본교,운영,대구광역시 군위군 의흥면 읍내리 283,대구광역시 군위군 의흥면 읍내길 67-17,7240000,대구광역시교육청,8862000,대구광역시군위교육지원청,2013-11-29,2024-07-09,36.175262,128.718112,2024-09-20,B555223,재단법인한국지방교육행정연구재단

#### 시도교육청명 이 '부산'으로 시작하는 정보만 발췌

In [6]:
df_school_info['시도교육청명'].str.contains('부산')

0        False
1         True
2        False
3        False
4        False
         ...
11984    False
11985    False
11986    False
11987    False
11988    False
Name: 시도교육청명, Length: 11989, dtype: bool

In [7]:
df_busan_school_info = df_school_info[df_school_info['시도교육청명'].str.contains('부산')]

In [8]:
df_busan_school_info.tail(2)

,학교ID,학교명,학교급구분,설립일자,설립형태,본교분교구분,운영상태,소재지지번주소,소재지도로명주소,시도교육청코드,시도교육청명,교육지원청코드,교육지원청명,생성일자,변경일자,위도,경도,데이터기준일자,제공기관코드,제공기관명
11804,B000002655,괘법초등학교,초등학교,1982-03-25,공립,본교,운영,부산광역시 사상구 괘법동 556-2,부산광역시 사상구 사상로161번길 8,7150000,부산광역시교육청,7201000,부산광역시북부교육지원청,2013-11-29,2024-07-09,35.160182,128.985798,2024-09-20,B555223,재단법인한국지방교육행정연구재단
11826,B000008618,양운중학교,중학교,1998-05-01,공립,본교,운영,부산광역시 해운대구 좌동 1373,부산광역시 해운대구 좌동순환로99번길 7,7150000,부산광역시교육청,7211000,부산광역시해운대교육지원청,2013-11-29,2024-07-09,35.175432,129.166697,2024-09-20,B555223,재단법인한국지방교육행정연구재단

In [9]:
df_busan_school_info.head(2)

,학교ID,학교명,학교급구분,설립일자,설립형태,본교분교구분,운영상태,소재지지번주소,소재지도로명주소,시도교육청코드,시도교육청명,교육지원청코드,교육지원청명,생성일자,변경일자,위도,경도,데이터기준일자,제공기관코드,제공기관명
1,B000002705,상당초등학교,초등학교,1997-03-01,공립,본교,운영,부산광역시 해운대구 좌동 1405,부산광역시 해운대구 세실로 173,7150000,부산광역시교육청,7211000,부산광역시해운대교육지원청,2013-11-29,2024-07-09,35.179656,129.176031,2024-09-20,B555223,재단법인한국지방교육행정연구재단
36,B000002619,신금초등학교,초등학교,1995-03-02,공립,본교,운영,부산광역시 북구 금곡동 1109,부산광역시 북구 효열로 42,7150000,부산광역시교육청,7201000,부산광역시북부교육지원청,2013-11-29,2024-07-09,35.250870,129.014795,2024-09-20,B555223,재단법인한국지방교육행정연구재단

#### 학교급구분 이 '초등학교' 인 곳 필터링

In [10]:
df_busan_school_info['학교급구분'].str.contains('초등학교')

1         True
36        True
50        True
52       False
80        True
         ...
11738     True
11740    False
11793     True
11804     True
11826    False
Name: 학교급구분, Length: 616, dtype: bool

In [11]:
df_busan_elementry_info = df_busan_school_info[df_busan_school_info['학교급구분'].str.contains('초등학교')]

In [12]:
df_busan_elementry_info.tail()

,학교ID,학교명,학교급구분,설립일자,설립형태,본교분교구분,운영상태,소재지지번주소,소재지도로명주소,시도교육청코드,시도교육청명,교육지원청코드,교육지원청명,생성일자,변경일자,위도,경도,데이터기준일자,제공기관코드,제공기관명
11711,B000002712,배산초등학교,초등학교,1981-12-29,공립,본교,운영,부산광역시 수영구 망미동 920,부산광역시 수영구 망미배산로48번길 85-15,7150000,부산광역시교육청,7211000,부산광역시해운대교육지원청,2013-11-29,2024-07-09,35.177161,129.101937,2024-09-20,B555223,재단법인한국지방교육행정연구재단
11719,B000002503,가평초등학교,초등학교,1977-09-01,공립,본교,운영,부산광역시 부산진구 가야동 649-19,부산광역시 부산진구 가야대로482번길 87,7150000,부산광역시교육청,7181000,부산광역시남부교육지원청,2013-11-29,2024-07-09,35.148853,129.025767,2024-09-20,B555223,재단법인한국지방교육행정연구재단
11738,B000024979,부산삼육초등학교,초등학교,1949-06-04,사립,본교,운영,부산광역시 금정구 청룡동 2-6,부산광역시 금정구 금정도서관로 17,7150000,부산광역시교육청,7191000,부산광역시동래교육지원청,2013-12-02,2024-07-09,35.272763,129.094750,2024-09-20,B555223,재단법인한국지방교육행정연구재단
11793,B000002470,감천초등학교,초등학교,1952-03-28,공립,본교,운영,부산광역시 사하구 감천동 212,부산광역시 사하구 원양로 368-2,7150000,부산광역시교육청,7171000,부산광역시서부교육지원청,2013-11-29,2024-07-09,35.082574,129.007193,2024-09-20,B555223,재단법인한국지방교육행정연구재단
11804,B000002655,괘법초등학교,초등학교,1982-03-25,공립,본교,운영,부산광역시 사상구 괘법동 556-2,부산광역시 사상구 사상로161번길 8,7150000,부산광역시교육청,7201000,부산광역시북부교육지원청,2013-11-29,2024-07-09,35.160182,128.985798,2024-09-20,B555223,재단법인한국지방교육행정연구재단

#### 학교 ID, 학교명, 설립일자, 소재지도로명주소, 위도, 경도 만 두고 나머지 삭제

In [13]:
df_busan_elem_last = df_busan_elementry_info[['학교ID', '학교명', '설립일자', '소재지도로명주소', '위도', '경도']]

In [14]:
df_busan_elem_last.tail()

,학교ID,학교명,설립일자,소재지도로명주소,위도,경도
11711,B000002712,배산초등학교,1981-12-29,부산광역시 수영구 망미배산로48번길 85-15,35.177161,129.101937
11719,B000002503,가평초등학교,1977-09-01,부산광역시 부산진구 가야대로482번길 87,35.148853,129.025767
11738,B000024979,부산삼육초등학교,1949-06-04,부산광역시 금정구 금정도서관로 17,35.272763,129.094750
11793,B000002470,감천초등학교,1952-03-28,부산광역시 사하구 원양로 368-2,35.082574,129.007193
11804,B000002655,괘법초등학교,1982-03-25,부산광역시 사상구 사상로161번길 8,35.160182,128.985798

#### 두개 데이터프레임 합치기

In [15]:
df_last_of_busan = pd.merge(df_busan_elementry, df_busan_elem_last, how='inner', left_on='학교명', right_on='학교명')

In [16]:
df_last_of_busan.to_excel('./2024년_부산_초교_정보최종.xlsx')

In [17]:
df_last_of_busan.tail()

,지역,정보공시 학교코드,학교명,설립구분,제외여부,1학년 학생수,2학년 학생수,3학년 학생수,4학년 학생수,5학년 학생수,6학년 학생수,총학생수,교사수,학교ID,설립일자,소재지도로명주소,위도,경도
301,강서구,S020002257,명일초등학교,공립,N,157,164,146,152,140,113,885,47,B000024936,2019-05-01,부산광역시 강서구 명지국제5로 170-5,35.109517,128.922704
302,강서구,S020002276,명원초등학교,공립,N,230,224,247,243,239,231,1422,69,B000024939,2020-05-01,부산광역시 강서구 명지국제6로 147,35.094128,128.914935
303,기장군,S020002277,일광초등학교,공립,N,187,174,191,178,178,176,1090,53,B000025605,2020-03-01,부산광역시 기장군 일광읍 해빛로 46,35.268118,129.222903
304,기장군,S020002312,해빛초등학교,공립,N,156,194,180,179,143,129,988,46,B000025609,2021-03-01,부산광역시 기장군 일광면 해빛6로 9,35.264498,129.221462
305,강서구,S020002361,명문초등학교,공립,N,245,232,202,153,118,64,1022,45,B000024940,2023-03-01,부산광역시 강서구 명지국제8로 195,35.099788,128.913911

#### 지도 표시

In [95]:
busan_center = [35.1379222, 129.05562775]
map = folium.Map(busan_center, tiles="OpenStreetMap", zoom_start=11)
map

In [97]:
geo_str = json.load(open('./busan_gu.json', encoding='utf-8'))

folium.GeoJson(geo_str, name='json_data').add_to(map)
map

#### 각 학교 위경도로 지도에 표시

In [98]:
sch_cluster = MarkerCluster().add_to(map)

for _, i in df_last_of_busan.iterrows():
    # 학생수가 적은 학교는 표시 안하도록 변경할 꺼임
    # print(i['위도'], i['경도']) ## 총학생수, 학교명, 설립구분, 소재지도로명주소
    Marker(location= [i['위도'], i['경도']],
           popup=f"{i['학교명']} / {i['총학생수']}명",
           icon=folium.Icon(color='blue')).add_to(sch_cluster)

In [65]:
map

#### 이제 아파트 정보 매핑

- 20241213_부산아파트_기본정도.xlsx에서 시작

In [22]:
df_busan_apts = pd.read_excel('./20241213_부산아파트_기본정보.xlsx')

In [24]:
df_busan_apts.tail()

,시도,시군구,읍면,동리,단지코드,단지명,단지분류,법정동주소,우편번호,도로명주소,...,외부인개방여부(지상),외부인개방여부(지하),이용가능시작시간(지상),이용가능시작시간(지하),이용종료시작시간(지상),이용종료시작시간(지하),전기차충전시설(상세),전기차 충전시설 설치대수(지상),전기차 충전시설 설치대수(지하),입주편의시설
1351,부산광역시,기장군,철마면,고촌리,A61987102,고촌센트럴아파트,아파트,부산광역시 기장군 철마면 고촌리 684 고촌센트럴아파트,46051.0,부산광역시 기장군 고촌로 11,...,입주민전용,입주민전용,NaN,0시 0분,NaN,0시 0분,"◆1◆|지하|스탠드형충전기|AC3상 7핀|급속|1|한국전력공사|,◆2◆|지하|벽부형...",0.0,11.0,없음
1352,부산광역시,기장군,철마면,고촌리,A61987101,고촌휴먼시아,아파트,부산광역시 기장군 철마면 고촌리 615 고촌휴먼시아,46051.0,부산광역시 기장군 고촌로44번길 16,...,NaN,외부인허용,시 분,0시 0분,시 분,23시 59분,"◆1◆|지하|벽부형충전기|AC단상 5핀|완속|6|파워큐브코리아|,◆2◆|지하|벽부형...",0.0,23.0,없음
1353,부산광역시,기장군,철마면,고촌리,A10027639,현대프라힐스동부산,아파트,부산광역시 기장군 철마면 고촌리 668 현대프라힐스동부산,46051.0,부산광역시 기장군 고촌로18번길 58,...,NaN,입주민전용,NaN,24시 0분,NaN,24시 0분,◆1◆|지하|벽부형충전기|DC콤보 7핀|완속|11|GS|,0.0,11.0,없음
1354,부산광역시,사하구,NaN,NaN,A10022280,두산위브더센트럴사하,NaN,부산광역시 사하구 장림로 199 두산위브더센트럴사하,NaN,NaN,...,NaN,입주민전용,NaN,0시 0분,NaN,24시 0분,"◆1◆|지하|스탠드형충전기|직접입력|완속|5|코스텔(주)|,◆2◆|지하|스탠드형충전...",0.0,6.0,없음
1355,부산광역시,해운대구,NaN,NaN,A10022405,드파인센텀아파트,NaN,부산광역시 해운대구 선수촌로30(반여동1349) 드파인센텀아파트,NaN,NaN,...,NaN,입주민전용,시 분,0시 0분,시 분,24시 0분,"◆1◆|지하|벽부형충전기|직접입력|완속|50|(주)코스텔|,◆2◆|지하|스탠드형충전...",0.0,56.0,없음

- 필요한 컬럼만 추출
    - 시도, 법정동주소, 우편번호, 도로명주소, 사용승인일, 동수, 세대수, 최고층수 만 사용

In [32]:
df_busan_apts[['시도', '우편번호', '법정동주소', '도로명주소', '사용승인일', '동수', '세대수', '최고층수']]

,시도,우편번호,법정동주소,도로명주소,사용승인일,동수,세대수,최고층수
0,부산광역시,48917.0,부산광역시 중구 영주동 161 영주동금호타운,부산광역시 중구 영주로 51,19970828.0,1,322.0,16
1,부산광역시,48905.0,부산광역시 중구 영주동 160 영주동아11블럭아파트,부산광역시 중구 영주로 65,19981030.0,2,328.0,16
2,부산광역시,48905.0,부산광역시 중구 영주동 92 영주동아아파트9B,부산광역시 중구 영주로 73,19981030.0,2,204.0,16
3,부산광역시,NaN,부산광역시 중구 영주동 5- 우남이채롬아파트,NaN,20060306.0,1,111.0,18
4,부산광역시,NaN,부산광역시 중구 대창동1가 54-67 부원아파트,NaN,19721104.0,1,142.0,12
...,...,...,...,...,...,...,...,...
1351,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 684 고촌센트럴아파트,부산광역시 기장군 고촌로 11,20140103.0,11,474.0,15
1352,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 615 고촌휴먼시아,부산광역시 기장군 고촌로44번길 16,20100104.0,12,1085.0,15
1353,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 668 현대프라힐스동부산,부산광역시 기장군 고촌로18번길 58,20160224.0,8,468.0,14
1354,부산광역시,NaN,부산광역시 사하구 장림로 199 두산위브더센트럴사하,NaN,20240926.0,13,1643.0,35
1355,부산광역시,NaN,부산광역시 해운대구 선수촌로30(반여동1349) 드파인센텀아파트,NaN,20240627.0,8,750.0,28

In [33]:
df_apt_total = df_busan_apts[['시도', '우편번호', '법정동주소', '도로명주소', '사용승인일', '동수', '세대수', '최고층수']]

In [44]:
df_apt_total.tail()

,시도,우편번호,법정동주소,도로명주소,사용승인일,동수,세대수,최고층수
1351,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 684 고촌센트럴아파트,부산광역시 기장군 고촌로 11,20140103.0,11,474.0,15
1352,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 615 고촌휴먼시아,부산광역시 기장군 고촌로44번길 16,20100104.0,12,1085.0,15
1353,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 668 현대프라힐스동부산,부산광역시 기장군 고촌로18번길 58,20160224.0,8,468.0,14
1354,부산광역시,NaN,부산광역시 사하구 장림로 199 두산위브더센트럴사하,NaN,20240926.0,13,1643.0,35
1355,부산광역시,NaN,부산광역시 해운대구 선수촌로30(반여동1349) 드파인센텀아파트,NaN,20240627.0,8,750.0,28

In [46]:
df_apt_total.to_excel('./24_부산아파트_필수정보.xlsx', index=False)

- geopy 모듈 설치
    - 잘안됨!

In [35]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl.metadata (1.4 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.4.1

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [37]:
from geopy.geocoders import Nominatim

In [ ]:
#데이터의 좌표주소 열을 이용해 지오코딩
geoloc = Nominatim(user_agent='South Korea', timeout=None)

for i, loc in enumerate(df_apt_total['도로명주소']):
    geo = geoloc.geocode(loc.split(',')[0])
    print(geo)

##### 24_부산아파트_필수정보.xlsx 구글드라이브 업로드
- Geocode by Awesome Table 사용하여 위경도 받기
- 가장 빠르고 정확함

- 완료한 파일 - 부산아파트_위경도_정리.xlsx

In [47]:
df_last_apt = pd.read_excel('./부산아파트_위경도_정리.xlsx')
df_last_apt.tail()

,시도,우편번호,법정동주소,Latitude,Longitude,도로명주소,사용승인일,동수,세대수,최고층수
1351,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 684 고촌센트럴아파트,35.238338,129.170897,부산광역시 기장군 고촌로 11,20140103.0,11,474,15
1352,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 615 고촌휴먼시아,35.241566,129.168216,부산광역시 기장군 고촌로44번길 16,20100104.0,12,1085,15
1353,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 668 현대프라힐스동부산,35.239013,129.168113,부산광역시 기장군 고촌로18번길 58,20160224.0,8,468,14
1354,부산광역시,NaN,부산광역시 사하구 장림로 199 두산위브더센트럴사하,35.082595,128.970869,NaN,20240926.0,13,1643,35
1355,부산광역시,NaN,부산광역시 해운대구 선수촌로30(반여동1349) 드파인센텀아파트,35.196714,129.118713,NaN,20240627.0,8,750,28

- df_busan_apts 에서 단지명 빼먹음!!

In [48]:
df_busan_apts[['단지명']]

              단지명
0         영주동금호타운
1     영주동아11블럭아파트
2       영주동아아파트9B
3        우남이채롬아파트
4           부원아파트
...           ...
1351     고촌센트럴아파트
1352       고촌휴먼시아
1353    현대프라힐스동부산
1354   두산위브더센트럴사하
1355     드파인센텀아파트

[1356 rows x 1 columns]

In [49]:
df_last_apt['단지명'] = df_busan_apts[['단지명']]

In [51]:
df_last_apt.tail()

,시도,우편번호,법정동주소,Latitude,Longitude,도로명주소,사용승인일,동수,세대수,최고층수,단지명
1351,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 684 고촌센트럴아파트,35.238338,129.170897,부산광역시 기장군 고촌로 11,20140103.0,11,474,15,고촌센트럴아파트
1352,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 615 고촌휴먼시아,35.241566,129.168216,부산광역시 기장군 고촌로44번길 16,20100104.0,12,1085,15,고촌휴먼시아
1353,부산광역시,46051.0,부산광역시 기장군 철마면 고촌리 668 현대프라힐스동부산,35.239013,129.168113,부산광역시 기장군 고촌로18번길 58,20160224.0,8,468,14,현대프라힐스동부산
1354,부산광역시,NaN,부산광역시 사하구 장림로 199 두산위브더센트럴사하,35.082595,128.970869,NaN,20240926.0,13,1643,35,두산위브더센트럴사하
1355,부산광역시,NaN,부산광역시 해운대구 선수촌로30(반여동1349) 드파인센텀아파트,35.196714,129.118713,NaN,20240627.0,8,750,28,드파인센텀아파트

- 최종 다시 저장

In [52]:
df_last_apt.to_csv('./부산아파트_위경도_정리.csv', encoding='utf-8')

##### 아파트 표시

In [99]:
apt_cluster = MarkerCluster().add_to(map)

for _, i in df_last_apt.iterrows():
    if i['세대수'] >= 500:  ## 세대수가 500명을 넘어가는 아파트만 표시
        # print(i['위도'], i['경도']) ## 총학생수, 학교명, 설립구분, 소재지도로명주소
        Marker(location= [i['Latitude'], i['Longitude']],
            popup=f"{i['단지명']} / {i['세대수']}명",
            icon=folium.Icon(color='red')).add_to(apt_cluster)

In [100]:
map

#### 영어학원 정보 가져오기

In [70]:
df_academy1 = pd.read_excel('./부산_영어학원정보_위경도추가.xlsx', sheet_name='학원')

In [81]:
df_academy1 = df_academy1[['관할교육청명', '학원명', '주소', 'Latitude', 'Longitude']]

In [82]:
df_academy1.tail()

,관할교육청명,학원명,주소,Latitude,Longitude
395,해운대,워릭프랭클린초등어학원,"부산광역시 해운대구 해운대로469번길 8 , 1층 101호 (우동)",35.163680,129.144872
396,해운대,고려대학교이아이이(EIE)광안어학원,"부산광역시 수영구 호암로29번길 45 , 3층 (광안동)",35.154789,129.110446
397,해운대,라하잉글리시학원,"부산광역시 해운대구 중동2로34번길 15 , 105동 220호 (중동, 롯데캐슬스타)",35.165491,129.163658
398,해운대,해운대디와이비(DYB)최선어학원,"부산광역시 해운대구 세실로 87 , 201호 (좌동, 영진파스타)",35.172196,129.176049
399,해운대,이미지어학원,"부산광역시 해운대구 세실로69번길 24 , 401호 (좌동, 비와이씨)",35.171847,129.176302

In [73]:
df_academy2 = pd.read_excel('./부산_영어학원정보_위경도추가.xlsx', sheet_name='교습소')

In [74]:
df_academy2.tail()

,연번,관할교육청명,교습소명,계열,교습과정,주소,Latitude,Longitude,우편번호,전화번호
129,3219,해운대,삼성일광영어교습소,외국어,실용외국어(유아/초·중·고),"부산광역시 기장군 일광면 해빛로 45 , 303호 (일광면)",35.267148,129.223101,46008,NaN
130,3221,해운대,링키영어모전영어교습소,외국어,실용외국어(유아/초·중·고),"부산광역시 기장군 정관읍 정관로 387 , 누리타워 601호 일부 (정관읍)",35.334844,129.165643,48075,NaN
131,3224,해운대,글로벌다빈치잉글리시도서관영어교습소,외국어,실용외국어(유아/초·중·고),"부산광역시 해운대구 좌동순환로433번길 33 , 302호 (중동, 리더스빌딩)",35.161691,129.176818,48096,NaN
132,3226,해운대,윤선생우리집앞영어교실해운대초영어교습소,외국어,실용외국어(유아/초·중·고),"부산광역시 해운대구 중동2로34번길 15 , 105동 219호 (중동, 롯데캐슬스타...",35.165491,129.163658,46048,NaN
133,3239,해운대,지앤비패럴랙스영어교습소,외국어,실용외국어(유아/초·중·고),"부산광역시 기장군 정관읍 정관1로 18 , 127동 203호 (정관읍, 이지 더원1...",35.338676,129.163851,48111,NaN

In [84]:
df_academy2 = df_academy2[['관할교육청명', '교습소명', '주소', 'Latitude', 'Longitude']]

In [87]:
df_academy2.columns = ['관할교육청명', '학원명', '주소', 'Latitude', 'Longitude']

In [88]:
df_academy = pd.concat([df_academy1, df_academy2])

In [89]:
df_academy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 534 entries, 0 to 133
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   관할교육청명     534 non-null    object
 1   학원명        534 non-null    object
 2   주소         534 non-null    object
 3   Latitude   534 non-null    float64
 4   Longitude  534 non-null    float64
dtypes: float64(2), object(3)
memory usage: 25.0+ KB

In [91]:
df_academy.tail()

,관할교육청명,학원명,주소,Latitude,Longitude
129,해운대,삼성일광영어교습소,"부산광역시 기장군 일광면 해빛로 45 , 303호 (일광면)",35.267148,129.223101
130,해운대,링키영어모전영어교습소,"부산광역시 기장군 정관읍 정관로 387 , 누리타워 601호 일부 (정관읍)",35.334844,129.165643
131,해운대,글로벌다빈치잉글리시도서관영어교습소,"부산광역시 해운대구 좌동순환로433번길 33 , 302호 (중동, 리더스빌딩)",35.161691,129.176818
132,해운대,윤선생우리집앞영어교실해운대초영어교습소,"부산광역시 해운대구 중동2로34번길 15 , 105동 219호 (중동, 롯데캐슬스타...",35.165491,129.163658
133,해운대,지앤비패럴랙스영어교습소,"부산광역시 기장군 정관읍 정관1로 18 , 127동 203호 (정관읍, 이지 더원1...",35.338676,129.163851

In [101]:
academy_cluster = MarkerCluster().add_to(map)

for _, i in df_academy.iterrows():
    # print(i['위도'], i['경도']) ## 총학생수, 학교명, 설립구분, 소재지도로명주소
    Marker(location= [i['Latitude'], i['Longitude']],
        popup=f"{i['학원명']}", # \n{i['주소']}",
        icon=folium.Icon(color='green')).add_to(academy_cluster)

In [102]:
map

In [103]:
map.save('./부산시_초교현황.html')